name: TWRP Cloud Builder
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev repo

    - name: Download TWRP Source
      run: |
        mkdir twrp && cd twrp
        git config --global user.name "kouki"
        git config --global user.email "kouki@example.com"
        repo init --depth=1 -u https://github.com -b twrp-12.1
        repo sync -c -j$(nproc) --no-tags --no-clone-bundle

    - name: Build Recovery Image
      run: |
        cd twrp
        echo "準備完了"

